version: '3.8'

services:
  # React app
  react-app:
    build:
      context: ./my-react-app
    ports:
      - "3001:80"
    volumes:
      - .:/app

  # Express back end
  express-backend:
    build:
      context: ./my-backend-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - react-app

