version: '3.8'

services:
  # Nginx reverse proxy
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.yml:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-app
      - express-backend

  # React app
  react-app:
    build:
      context: ./my-react-app
    expose:
      - "80"
    volumes:
      - .:/app


  # Express back end
  express-backend:
    build:
      context: ./my-backend-app
    expose:
      - "3000"
    volumes:
      - .:/app
    depends_on:
      - react-app


